// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Coolbooks.Models;

public partial class Author
{
    public int AuthorId { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public DateTime? Created { get; set; }

    public virtual ICollection<Book> Books { get; } = new List<Book>();
}