// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Coolbooks.Models;

public partial class Book
{
    public int BookId { get; set; }

    public int? UserId { get; set; }

    public int? AuthorId { get; set; }

    public int? GenreId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Isbn { get; set; }

    public string Imagepath { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? Created { get; set; }

    public virtual Author Author { get; set; }

    public virtual Genre Genre { get; set; }

    public virtual ICollection<Review> Reviews { get; } = new List<Review>();

    public virtual SiteUser User { get; set; }
}