// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Coolbooks.Models;

public partial class Comment
{
    public int CommentId { get; set; }

    public int? ParentCommentId { get; set; }

    public int? ReviewId { get; set; }

    public string Text { get; set; }

    public int? UserId { get; set; }

    public string Status { get; set; }

    public DateTime? Created { get; set; }

    public virtual ICollection<Comment> InverseParentComment { get; } = new List<Comment>();

    public virtual ICollection<Like> Likes { get; } = new List<Like>();

    public virtual Comment ParentComment { get; set; }

    public virtual Review Review { get; set; }

    public virtual SiteUser User { get; set; }
}