// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Coolbooks.Models;

public partial class Like
{
    public int LikeId { get; set; }

    public int? UserId { get; set; }

    public int? ReviewId { get; set; }

    public int? CommentId { get; set; }

    public string Like1 { get; set; }

    public virtual Comment Comment { get; set; }

    public virtual Review Review { get; set; }

    public virtual SiteUser User { get; set; }
}