// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Coolbooks.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int? BookId { get; set; }

    public string Id { get; set; }

    public string Title { get; set; }

    public string Text { get; set; }

    public int? Rating { get; set; }

    public DateTime? Created { get; set; }

    public string Status { get; set; }

    public virtual Book Book { get; set; }

    public virtual ICollection<Comment> Comments { get; } = new List<Comment>();

    public virtual AspNetUser IdNavigation { get; set; }

    public virtual ICollection<Like> Likes { get; } = new List<Like>();
}