// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Coolbooks.Models;

public partial class SiteUser
{
    public int UserId { get; set; }

    public int? UserinfoId { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public virtual ICollection<Book> Books { get; } = new List<Book>();

    public virtual ICollection<Review> Reviews { get; } = new List<Review>();

    public virtual Userinfo Userinfo { get; set; }
}