// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Coolbooks.Models;

public partial class Userinfo
{
    public int UserInfoId { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public DateTime? Created { get; set; }

    public string Role { get; set; }

    public virtual ICollection<SiteUser> SiteUsers { get; } = new List<SiteUser>();
}